### ISSUE TITLE
Non-scalar *Prop objects behave like handle objects, while scalar *Prop objects behave like value objects

### ISSUE THREAD

**Issue by DionTimmermann** [wollmich/metas-unclib-matlab-wrapper#22]
I am not sure, if this issue is avoidable, and if it should be avoided or rather documented.

Due to the internal implementation of the matlab wrapper, variables that contain arrays (`obj.IsArray == true`) behave as references to these arrays. When executing the following:

```
a = LinProp(rand(3, 3));
b = a;
a(1, 1) = 0;
```
b(1, 1) is also set to 0.

The same does not apply to variables that do not contain arrays (`obj.IsArray == false`). When executing the following:
```
a = LinProp(rand(1, 1));
b = a;
a(1, 1) = 0;
```
b(1, 1) is not set to 0.

I only noticed this distinction now and did not (easily) find a note about it in the documentation.

As far as I can see, it is not possible to overwrite the assignment operation (`b = a`) in matlab, thus it is not possible to easily change this behaviour. The only approach to prevent this behaviour that I can see is to [store LinProp matricies as matricies of scalar LinProp objects](https://de.mathworks.com/help/matlab/matlab_oop/creating-object-arrays.html), but I am quite sure that would require extensive code changes and likely also come with big performance costs.

Alternatively, by [deriving *Prop from the handle class](https://de.mathworks.com/help/matlab/matlab_oop/handle-objects.html), the behaviour of variables that do not contain arrays (`obj.IsArray == false`) could be changed. But I am not doubtfull that this is desirable heviour in practice.

Thus, it would likely be best to simply document this distinction and to unify the behaviour of the different assignment operations.

Currenty, the assignent operators behave as follows:
```
% The following assigment operations copy the reference:
b = a;
b = a();
b = LinProp(a);

% The following assigment operations copy the individual elements:
for yy=1:size(a, 1) for xx=1:size(a, 2) b(yy, xx) = a(yy, xx); end end
b = a(:, :);
b = copy(a);
```

I would suggest to change the `b = a();` assignment to copy the individual elements.

[Script used for testing the different assignment operators.](https://github.com/wollmich/metas-unclib-matlab-wrapper/files/6954941/copying.m.txt)

**Comment by wollmich** [comment]
> The only approach to prevent this behavior that I can see is to store LinProp matrices as matrices of scalar LinProp objects, but I am quite sure that would require extensive code changes and likely also come with big performance costs.

The original implementation of 2006 was like that. But this is **very slow** for matrix operations, like matrix multiplication. Either it calls `2*n^3` times the .NET library for multiplication and addition. Or it calls `3*n^2` times the .NET library for conversion.

I would propose that `b = a()` and `b = LinProp(a)` copy the individual elements of the matrix.

**Comment by wollmich** [comment]
If you take a look at the `NetObject` property you can see that for a scalar it's `UncNumber` or `Complex<UncNumber>`. Both of them are a C# structs. The value is copied on an assignment.

On the other hand for a matrix / an array the `NetObject` is `RealNArray<UncNumber>` or `ComplexNArray<UncNumber>`. Both of them are C# classes. Only the reference is copied on an assignment.

**Comment by DionTimmermann** [comment]
(Sorry, for closing the issue, I accidentally hit enter while reading.)

> I would propose that b = a(), b = [a] and b = LinProp(a) copy the individual elements of the matrix.
That also sound reasonable.

I just realized, that this issue might be fixed by always creating a copy of the individual elements when using subsasgn(). I will test this tomorrow. However, I am not sure how much this would decrease performacne.

**Comment by wollmich** [comment]
> I just realized, that this issue might be fixed by always creating a copy of the individual elements when using subsasgn().

I did a quick test in MATLAB with doubles and matrix which uses 32 GB of RAM. I doesn't create a copy in the `b = a` or `c = a` assignments. But It creates a copy in `subsasgn` method for `a(1, 1) = 0` and `a(3, 1) = 0` but not for `a(2, 1) = 0`.

So MATLAB isn't coping when it not necessary. 

```
>> memory
Maximum possible array:      120475 MB (1.263e+11 bytes) *
Memory available for all arrays:      120475 MB (1.263e+11 bytes) *
Memory used by MATLAB:        1334 MB (1.399e+09 bytes)
Physical Memory (RAM):      130988 MB (1.374e+11 bytes)

*  Limited by System Memory (physical + swap file) available.
>> a = rand(65536);
>> memory
Maximum possible array:       88650 MB (9.296e+10 bytes) *
Memory available for all arrays:       88650 MB (9.296e+10 bytes) *
Memory used by MATLAB:       34031 MB (3.568e+10 bytes)
Physical Memory (RAM):      130988 MB (1.374e+11 bytes)

*  Limited by System Memory (physical + swap file) available.
>> b = a;
>> memory
Maximum possible array:       88707 MB (9.302e+10 bytes) *
Memory available for all arrays:       88707 MB (9.302e+10 bytes) *
Memory used by MATLAB:       34044 MB (3.570e+10 bytes)
Physical Memory (RAM):      130988 MB (1.374e+11 bytes)

*  Limited by System Memory (physical + swap file) available.
>> a(1, 1) = 0;
>> memory
Maximum possible array:       57055 MB (5.983e+10 bytes) *
Memory available for all arrays:       57055 MB (5.983e+10 bytes) *
Memory used by MATLAB:       66814 MB (7.006e+10 bytes)
Physical Memory (RAM):      130988 MB (1.374e+11 bytes)

*  Limited by System Memory (physical + swap file) available.
>> a(2, 1) = 0;
>> memory
Maximum possible array:       56731 MB (5.949e+10 bytes) *
Memory available for all arrays:       56731 MB (5.949e+10 bytes) *
Memory used by MATLAB:       66811 MB (7.006e+10 bytes)
Physical Memory (RAM):      130988 MB (1.374e+11 bytes)

*  Limited by System Memory (physical + swap file) available.
>> c = a;
>> a(3, 1) = 0;
>> memory
Maximum possible array:       24881 MB (2.609e+10 bytes) *
Memory available for all arrays:       24881 MB (2.609e+10 bytes) *
Memory used by MATLAB:       99580 MB (1.044e+11 bytes)
Physical Memory (RAM):      130988 MB (1.374e+11 bytes)

*  Limited by System Memory (physical + swap file) available.
>> 
```

**Comment by DionTimmermann** [comment]
OK, as far as I understand, in the following example the actual data are only copied in the third line, when one of the elements is changed. (This also explains, why there is no large performance panalty in matlab, when a variable is passed to a function "by value".)
```
a = rand(65536);
b = a;
a(1,1) = 0;
```

We can replicate this behaviour in the uncLib by introducing a copy command inside subsasgn. I have created a new branch to test these changes. You can find it here: https://github.com/DionTimmermann/metas-unclib-matlab-wrapper/tree/remove-sideeffects-in-subsasgn . This change increases computational time and memory requirements.

**Computational Time**
Copying the `NetObject` obviously takes time. I have not yet found a good way to quanity or compare this time. If only one value of a large matrix is changed (`a=LinProp(rand(3000)); profile on; a(1, 1) = 0; profile viewer`) subsasgn the copy operation requires up to about 60% of the compute time of subsasgn(). If all values of a large matrix are changed to a newly calculated value (`a=LinProp(rand(3000)); profile on; a(:,:) = a(:,:).*a(:,:); profile viewer`), the copy operation requires negligable time.

**Memory Requirements**
This change increases the memory requirements for modifiying a matrix, as the matrix is copied at least temporarily.  In statements like the following, there temporarily exist two `NetObject`s of type `RealNArray<UncNumber>` or `ComplexNArray<UncNumber>`, one for a before the assignment and one for a after the assignment.
```
a = LinProp(rand(1000));
a(1,1) = 0;
```
However, the `NetObject` for the matrix is small compared to the individual unc variables inside it. The origial `NetObject` is automatically freed by the garbage collector.

I modified one entry of a 3000-by-3000 LinProp matrix 1000 times. As you can see, after a short time, the garbage collector kicks in regularly: 
![2021-08-10 11_07_42-Figure 1](https://user-images.githubusercontent.com/14871355/128840214-8f73c93b-069c-49f8-af6e-243b7b75f36f.png)

Here is the code I used for the test:
```
N = 1000;
mem = zeros(1, N);

n = 1;

[u, ~] = memory;
mem(n) = u.MemUsedMATLAB;
n = n+1;

a = LinProp(rand(3000));

[u, ~] = memory;
mem(n) = u.MemUsedMATLAB;
n = n+1;

while n<N
    
    a(1, 1) = 0;
    
    [u, ~] = memory;
    mem(n) = u.MemUsedMATLAB;
    
    n = n+1;
end
plot(mem);
```

**Comment by wollmich** [comment]
I agree that `b = a()` and `b = [a]` should create a copy and `b = LinProp(a)` should not create a copy.

**Comment by wollmich** [comment]
Another idea:

````
>> a = LinProp(rand(3));
>> b = a;
>> c = b(); % Copy
>> a.NetObject.GetHashCode

ans =

  int32

   45310401

>> b.NetObject.GetHashCode

ans =

  int32

   45310401

>> c.NetObject.GetHashCode

ans =

  int32

   5140427
````

If the hash code of the reference is unique for all variables in the MATLAB workspace, then there is not need for a copy in `subsasgn`.

There is a small change that a copy is done when it was not needed, see https://stackoverflow.com/a/4994372/7556646.

What do you think?

**Comment by wollmich** [comment]
> Do not test for equality of hash codes to determine whether two objects are equal. (Unequal objects can have identical hash codes.) To test for equality, call the ReferenceEquals or Equals method.

See https://docs.microsoft.com/en-us/dotnet/api/system.object.gethashcode?view=net-5.0.

So a better solution would be:

````
>> System.Object.ReferenceEquals(a.NetObject, b.NetObject)

ans =

  logical

   1

>> System.Object.ReferenceEquals(a.NetObject, c.NetObject)

ans =

  logical

   0

>> 
````

See https://docs.microsoft.com/en-us/dotnet/api/system.object.referenceequals?view=net-5.0

**Comment by wollmich** [comment]
> I am afraid I do not see, how this could help.

My idea is to create a `copyifneeded` method which is used in the `subsasgn` method.

This method should check:

1. If the current matrix in `subsasgn` is `LinProp`.
2. If the `NetObject` is a `RealNArray<UncNumber>` or a `ComplexNArray<UncNumber>` object.
3. List all variables in the workspace of MATLAB using `who`.
4. Iterate trough all variables and check if is `LinProp`.
5. Check if the `NetObject` is a `RealNArray<UncNumber>` or a `ComplexNArray<UncNumber>` object.
6. Check if any variable has the same reference as the current matrix using `System.Object.ReferenceEquals`.
7. Copy the `LinProp` matrix.

The point I'm not so sure about is the list all variables in the workspace of MATLAB using `who`.

**Comment by DionTimmermann** [comment]
Using `who` could indeed be a solution. (Although the complexity kind of scares me of.) 

We would have to ckeck in all variables in all workspaces, but that could work using a combination of who, [evalin, dbup and dbdown](https://de.mathworks.com/help/matlab/ref/evalin.html#mw_29b55d3e-dc8b-4e6a-b17a-4e109c8ef358). Technically, we would also have to check all variables that are stored in objects - which would not work with private/protected variables...

It would be so much easier (and less error prone!) if matlab used the constructor or an overloadable method when copying an object...

**Comment by wollmich** [comment]
> Using `who` could indeed be a solution. (Although the complexity kind of scares me of.

I think as well it to error prone.

> From how I currently see it, there are 4 "good solutions". I currently do not see how any of these could be implemented.

I think none of them are possible. `b=a` can not be overloaded.
See https://ch.mathworks.com/help/matlab/matlab_oop/operations-with-objects.html.

> And there are 3 non-ideal solutions that could be implemented but also have drawbacks.

> We always use copy in subsasgn.

No. Too much of a performance drawback.

> We make scalars behave the same way as matricies (I think my least favorit solution...)

No.

> We leave the problem as is and simply document it.

I've we don't find a solution I would prefer to add a note to the documentation.

**Comment by wollmich** [comment]
By the way: are you aware of
https://ch.mathworks.com/help/matlab/matlab_prog/copying-objects.html
and 
https://ch.mathworks.com/help/matlab/matlab_oop/custom-copy-behavior.html?

**Comment by DionTimmermann** [comment]
Yes, I was aware of both documents, although I have not worked with `matlab.mixin.Copyable` before. From what I understand, *Prop matricies currently behave exactly like objects derived from `matlab.mixin.Copyable`. Both behave like handles and both implement a `copy()` method to create a copy of the object.

I have already confirmed in tests that `matlab.mixin.Copyable` does **not** invoke the `copy()` method on statements like `b=a`, where `a` is a subclass of `matlab.mixin.Copyable`.

I edited the title of the issue to reflect the nomenclature in https://ch.mathworks.com/help/matlab/matlab_prog/copying-objects.html.

**Comment by wollmich** [comment]
I've added the following subsection to Introduction section of the user reference of METAS UncLib MATLAB:

![image](https://user-images.githubusercontent.com/22192118/129558046-a92ad5cf-1759-4524-81a5-faddb38a92a5.png)

Feel free to comment.

BTW: I'll soon release METAS VNA Tools V2.4.9 and METAS UncLib V2.4.9.

**Comment by wollmich** [comment]
> We leave the problem as is and simply document it.

I've added it to the documentation of METAS UncLib MATLAB, see above. Therefor I gonna close this issue. We can reopen it once we have a better solution.
