### ISSUE TITLE
get_stdunc(abs(num_comp)) returns NaN for complex numbers with a nominal value of zero.

### ISSUE THREAD

**Issue by DionTimmermann** [wollmich/metas-unclib-matlab-wrapper#28]
As can be seen in the example below,` get_stdunc(abs(num_comp))` returns NaN for complex numbers with a nominal value of zero.

The effect seems to occure when num_comp  is a complex number with an nominal value of 0, regardless of the standard uncerntainty. Based on the implementation of `abs()` in `LinProp.m`, I suspect that the issue originates in the UncLib itself.

```
real = LinProp(0, 1);
imag = LinProp(0, 1);
num_comp = real+1i*imag;

get_stdunc(abs(num_comp)) % NaN
```

**Comment by DionTimmermann** [comment]
I have removed mentions of `abs(get_stdunc(num_comp))`, as that is a different calculation.

**Comment by wollmich** [comment]
The absolute value of a `Complex<UncNumber>` is implemented as described by the following C# code inside the METAS UncLib:

````
double a = _a.Value;
double b = _b.Value;
double c;
if (a == 0 && b == 0)
{
    c = System.Math.Sqrt(System.Math.Pow(a, 2) + System.Math.Pow(b, 2));
}
else if (System.Math.Abs(a) >= System.Math.Abs(b))
{
    c = System.Math.Abs(a) * System.Math.Sqrt(1 + System.Math.Pow(b / a, 2));
}
else
{
    c = System.Math.Abs(b) * System.Math.Sqrt(1 + System.Math.Pow(a / b, 2));
}
double diff_c_a = a / c;
double diff_c_b = b / c;
````

In your example `c` is equal to zero and `diff_c_a` and `diff_c_b` will be `NaN`.

So the `stdunc` of  `c` will be `NaN`.

This is a limitation of `LinProp`, try `MCProp`.

````
>> real = MCProp(0, 1);
>> imag = MCProp(0, 1);
>> abs(real + 1i.*imag)
 
ans = 
 
   (1.25298 ± 0.653885)

>> hist(double(ans.NetObject.values), 81)
````

![Hist](https://user-images.githubusercontent.com/22192118/130647862-e712628b-8e35-45ef-9ef0-d8d3d1109ba7.png)
