### ISSUE TITLE
Dot product result is numerically different for double and unc variables

### ISSUE THREAD

**Issue by DionTimmermann** [wollmich/metas-unclib-matlab-wrapper#5]
The result of the dot product (e.g. `rand(1, 5)*rand(5, 1)`) is sometimes different for double and unc variables. The difference does not always occur and seems to grow when the vector sizes increase. At the moment, I do not consider this to be a severe issue, as it is numerically small and I am unaware of cases where this operation is used frequently. Still, I wanted to document the issue.

As one can see from the table below, the error seems to grow with an increasing length of the vectors. At first I thought this would be the result of small multiplication errors being added up, but this does not fit the "large" error for the 1e6 and 1e7 vectors.

    Vector Length    Tests    Fail Rate [%]    MaxErrorAbs    MaxErrorRel
    _____________    _____    _____________    ___________    ___________

            1        1000            0                  0              0 
            2        1000            0                  0              0 
            3        1000         23.3         4.4409e-16     2.4834e-16 
            4        1000         24.8         4.4409e-16     2.2137e-16 
            5        1000         30.5         4.4409e-16     3.8151e-16 
           10        1000         43.6         1.3323e-15     4.1611e-16 
           20        1000         60.5         3.5527e-15     6.4391e-16 
           30        1000         66.7         5.3291e-15     6.0795e-16 
           40        1000         69.6         8.8818e-15     8.7399e-16 
           50        1000         76.3         1.4211e-14     8.8666e-16 
          100        1000         80.2         2.1316e-14     1.0057e-15 
          200        1000         84.5         7.1054e-14     1.4658e-15 
          300        1000         85.1         1.8474e-13      2.317e-15 
          400        1000         90.6         2.1316e-13      2.109e-15 
          500        1000         90.5         2.2737e-13     1.7917e-15 
         1000          10           90         6.2528e-13     2.6002e-15 
        10000          10          100         1.5916e-11     6.3902e-15 
        1e+05          10          100         2.7285e-10     1.0926e-14 
        1e+06          10          100         6.4028e-09     2.5644e-14 
        1e+07          10          100         2.7986e-07     1.1189e-13 

The code used to create the table above is:
```
unc = @LinProp;

data = table([], [], [], [], [], 'Variablenames', {'Vector Length', 'Tests', 'Fail Rate [%]', 'MaxErrorAbs', 'MaxErrorRel'});
vectorElements = [1 2 3 4 5 10 20 30 40 50 100 200 300 400 500 1000 1e4 1e5 1e6 1e7];

for ii = 1:length(vectorElements)
    maxErrorAbs = 0;
    maxErrorRel = 0;
    fails = 0;
    if vectorElements(ii) < 1000
        tests = 1000;
    else
        tests = 10;
    end
    for kk = 1:tests
        a = rand(1, vectorElements(ii));
        b = rand(vectorElements(ii), 1);
        res_dbl = a*b;
        res_unc = LinProp(a) * LinProp(b);
        
        if res_dbl ~= double(res_unc)
            fails = fails + 1;
            maxErrorAbs = max(maxErrorAbs, abs(double(res_unc) - res_dbl));
            maxErrorRel = max(maxErrorRel, abs(double(res_unc) - res_dbl)/res_dbl);
        end
        clear a b res_dbl res_unc
    end
    data{ii, :} = vectorElements(ii);
    data{ii, 2} = kk;
    data{ii, 3} = fails/kk*100;
    data{ii, 4} = maxErrorAbs;
    data{ii, 5} = maxErrorRel;
    
    fprintf('%s: Finished %i/%i.\n', datestr(clock), ii, length(vectorElements));
    
end

disp(data)
```

**Comment by wollmich** [comment]
This problem comes from adding a small and a large double. Let's assume 3 variables. One large and two small numbers. The order of adding them up can change the result.

See the following example code:

```
>> a = 1 + eps/2 + eps/2;
>> a - 1

ans =

     0

>> b = eps/2 + eps/2 + 1;
>> b - 1

ans =

   2.2204e-16

>> 
```

In my dot method I've a for loop which goes through the vector elements and multiplies them and finally adds them up. 

On the other side MATLAB is using Intel MKL (BLAS) to perform the dot function. There the loop is parallelized. So the order is not the same.

Hope this helps.

**Comment by wollmich** [comment]
See as well <https://software.intel.com/content/www/us/en/develop/documentation/onemkl-linux-developer-guide/top/obtaining-numerically-reproducible-results.html>.
