### ISSUE TITLE
Error displaying scalars with very large or very small components.

### ISSUE THREAD

**Issue by DionTimmermann** [wollmich/metas-unclib-matlab-wrapper#61]
Pull-request #58 introduced an error.

Displaying scalars with very large or very small components causes incorrect results, e.g. `LinProp(1e-20)`.

**Comment by DionTimmermann** [comment]
I will fix this tomorrow.

**Comment by wollmich** [comment]
I'm asking myself if this was a good idea.

> I would like to see that every thing gets formatted as double and not as integer,

See https://github.com/wollmich/metas-unclib-matlab-wrapper/pull/58#issuecomment-1128863778.

And you answered: 

> Personally, I like that matlab tries to display integers as integers (even when they are saved as a double). 

See https://github.com/wollmich/metas-unclib-matlab-wrapper/pull/58#discussion_r875508496.

Using the current approach the output is like that:

```
>> a = LinProp(1, 1e-2)

a =

   (1.0000 ± 0.0100)

>> b = LinProp(1, 1e-6)

b =

   (1.0000 ± 0.0000)

>> format long
>> b

b =

   (1.000000000000000 ± 0.000001000000000)

>> format shortE
>> b

b =

   (1.0000e+00 ± 1.0000e-06)

>> format shortG
>> b

b =

   (1 ± 1e-06)
```

Will writing the above example I think I still like the current approach.

On the other hand your output (format each element) would look like this:

```
>> a = LinProp(1, 1e-2)

a =

   (1 ± 0.0100)

>> b = LinProp(1, 1e-6)

b =

   (1 ± 1.0000e-06)
```

The problem I've is that in the mean I like as well the second approach which hasn't this issue https://github.com/wollmich/metas-unclib-matlab-wrapper/issues/61.

I think I should sleep one night over it and we should decide tomorrow.

**Comment by DionTimmermann** [comment]
Yeah, while I prefer the second aproach, I also see the point in the current appraoch. Honestly, I think what is best depends on the data, i.e. if you are able to reach ppm's over even lower precision and if all entries in a matrix / the real and imag part are similar in size.

I see the following approaches to solve #61.
1. **Catch and display the common exponent.**
```
>> LinProp(10e2, 10e-3)

ans =

    1.0e+03 *

    (1.0000  ±  0.0000)

```
- Pro: Numbers have mostly uniform length/formatting.
- Con: Values with ppm or better precision often lead the StdUnc being 0.0000.
- Con: I am slightly worried that we miss some special case such as #61.
2. **Revert back to the second approach.**
- Pro: Robust implementation
- Pro: The output tends to be shorter.
- Con: Numbers vary in formatting.
3. **Detect if there is a common exponent and only then use the second approach.**
- Pro: More robust than 1, and numbers have mostly uniform length/formatting.
- Con: Values with ppm or better precision often lead the StdUnc being 0.0000.
- Con: Numbers can vary in formatting.
5. **Use sprintf.**
- Con: We need a lot of special cases for the different formats.
- Con: The exponent notation is not even used for very large numbers, resulting in very long outputs.
- Con: Standard uncertainties smaller than 1e-6 will be displayed as 0.0000, even if the value of the number is also very small.
- Pro: Except me, no one has complained so far.

**Comment by wollmich** [comment]
I propose to go back to the second approach.
