### ISSUE TITLE
Constructor with 'system' does not test variables to be real-valued.

### ISSUE THREAD

**Issue by DionTimmermann** [wollmich/metas-unclib-matlab-wrapper#68]
The 'system' constructor is only defined for real-valued system inputs (RealUncNumber), but constructor does not check that the system inputs are non-complex. Instead, the constructor failes with an internal error message.
```
a = complex(LinProp(0, 0.1));
b = complex(LinProp(0, 0.1));
c = LinProp(0, [a, b], [1, 1], 'system')
Error using LinProp (line 209)
No method 'Init' with matching signature found for class 'Metas.UncLib.LinProp.UncNumber'.
 ```

I am mainly documenting this issue, as my first thought was "oh that's a bug". Only then did I notice that what I was trying to do was an illegal operation. Should this case be caught and another error message returned? (I am ambivalent about such issues. I like error messages that provide usefull information, but adding such checks might not be the most relevant thing to work on. Thus, feel free to close this issue as "won't  fix".)

**Comment by wollmich** [comment]
I would prefer to see an error message when one of the arguments is complex.
