### ISSUE TITLE
interpolation2(x, y, n, xx) returns (NaN ± NaN) if y has nan uncertainty, but interpolation(x, y, n, xx) does not.

### ISSUE THREAD

**Issue by DionTimmermann** [wollmich/metas-unclib-matlab-wrapper#79]
When LinProps with nan uncertainties are interpolated, `interpolation` behaves as expected:
```
>> interpolation([1, 2], [LinProp(1, nan), LinProp(2, nan)], 1, 1.5)

ans = 

  LinProp:

   (1.5000 ± NaN)
```
But `interpolation2` returns a variable with the nominal value of NaN, which is not expected and seems inconsistent.
```
>> interpolation2([1, 2], [LinProp(1, nan), LinProp(2, nan)], 1, 1.5)

ans = 

  LinProp:

   (NaN ± NaN)
```

**Comment by wollmich** [comment]
This is a bug in the C# code. I've fixed it. This fixed will be part of release V2.6.3.

Thank you for reporting.
